import { Injectable } from '@angular/core';

export interface CarListing {
  id: number;
  type: string;
  brand: string;
  model: string;
  transmission: string;
  seats: number;
  engine: string;
  to100km: string;
  horsePower: number;
  year: number;
  color: string;
  priceForDay: number;
  images: string[];
  city: string;
  availability?: { startTime: number; endTime: number }[];
}

@Injectable({
  providedIn: 'root',
})
export class MyDataService {
  now = Date.now();
  userMinEndDate: Date = new Date();
  userMaxEndDate: Date = new Date();
  city: string = '';
  timeDifference:any = 1
  daysDifference:any = 1

  constructor() {}

  private myDataArray: CarListing[] = [
    {
      id: 0,
      type: 'sedan',
      brand: 'Mercedes-Benz',
      model: 'S Class',
      transmission: 'Automatic',
      seats: 4,
      engine: '4.0L Biturbo V8',
      to100km: '3.7sec',
      horsePower: 603,
      year: 2017,
      color: 'red',
      priceForDay: 800,
      images: [
        'https://pugachev.miami/wp-content/uploads/2022/03/mercedes-benz-s-rentnal-miami1.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/03/mercedes-benz-s-rentnal-miami2.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/03/mercedes-benz-s-rentnal-miami3.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/03/mercedes-benz-s-rentnal-miami4.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/03/mercedes-benz-s-rentnal-miami5.jpg',
      ],
      city: 'Los Angeles',
      availability: [
        {
          startTime: this.now + 2 * 24 * 60 * 60 * 1000,
          endTime: this.now + 3 * 24 * 60 * 60 * 1000,
        },
      ],
    },
    {
      id: 1,
      type: 'sedan',
      brand: 'Mercedes',
      model: 'S550 SEDAN',
      transmission: 'Automatic',
      seats: 4,
      engine: '4.0L Biturbo V8',
      to100km: '3.6sec',
      horsePower: 603,
      year: 2019,
      color: 'black',
      priceForDay: 1100,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/03/tild3861-3763-4430-b064-643939636563__noroot.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/tild3061-3564-4332-b830-653639656233__s6-e1566062806105.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/s2.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/s3.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/tild3432-6630-4336-b161-663130386134__N6Z_0840.jpg',
      ],
      city: 'Los Angeles',
      availability: [
        {
          startTime: this.now + 4 * 24 * 60 * 60 * 1000,
          endTime: this.now + 5 * 24 * 60 * 60 * 1000,
        },
      ],
    },
    {
      id: 2,
      type: 'sedan',
      brand: 'Mercedes',
      model: 'C63S AMG Sedan',
      transmission: 'Automatic',
      seats: 4,
      engine: '4.0L Biturbo V8',
      to100km: '3.5sec',
      horsePower: 603,
      year: 2018,
      color: 'blue',
      priceForDay: 700,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/11/Mercedes-C63s-AMG-sedan-6.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Mercedes-C63s-AMG-sedan-5.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Mercedes-C63s-AMG-sedan-2.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Mercedes-C63s-AMG-sedan-4.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/merc.jpeg',
      ],
      city: 'Los Angeles',
      availability: [
        {
          startTime: this.now + 6 * 24 * 60 * 60 * 1000,
          endTime: this.now + 7 * 24 * 60 * 60 * 1000,
        },
      ],
    },
    {
      id: 3,
      type: 'cabriolet',
      brand: 'BMW',
      model: 'M4',
      transmission: 'Automatic',
      seats: 4,
      engine: '4.0L Biturbo V6',
      to100km: '4.1sec',
      horsePower: 603,
      year: 2019,
      color: 'blue',
      priceForDay: 600,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/03/IMG_9013.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/IMG_9008.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/IMG_9007.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/IMG_9009.jpg',
      ],
      city: 'Dubai',
    },
    {
      id: 4,
      type: 'cabriolet',
      brand: 'BMW',
      model: 'M850',
      transmission: 'Automatic',
      seats: 4,
      engine: '4.0L Biturbo',
      to100km: '3.8sec',
      horsePower: 603,
      year: 2020,
      color: 'white',
      priceForDay: 3000,
      images: [
        'https://pugachev.miami/wp-content/uploads/2020/03/BMW-M850-2020_1.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/03/BMW-M850-2020_3.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/03/BMW-M850-2020_2.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/03/BMW-M850-2020_4.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/03/BMW-M850-2020_5.jpg',
      ],
      city: 'Dubai',
    },
    {
      id: 5,
      type: 'cabriolet',
      brand: 'PORSCHE',
      model: '911 RED',
      transmission: 'Automatic',
      seats: 2,
      engine: '6-Cyl Turbo 3.0 Liter',
      to100km: '3.2 sec',
      horsePower: 480,
      year: 2022,
      color: 'red',
      priceForDay: 490,
      images: [
        // 'https://pugachev.miami/wp-content/uploads/2019/03/porshe-911-2-e1566062485434.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/03/porshe-911-5-e1566062292200.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/03/porshe-911-4-e1566062437858.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/03/porshe-933-3-e1566062451228.jpeg',
      ],
      city: 'Los Angeles',
    },
    {
      id: 6,
      type: 'cabriolet',
      brand: 'ROLLS-ROYCE',
      model: 'DAWN WHITE',
      transmission: 'Automatic 8-speed',
      seats: 4,
      engine: '6.6 L V12',
      to100km: '4,9 sec',
      horsePower: 563,
      year: 2021,
      color: 'white',
      priceForDay: 870,
      images: [
        'https://pugachev.miami/wp-content/uploads/2022/03/rolls-royce-dawn-rentnal-miami1.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/03/rolls-royce-dawn-rentnal-miami3.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/03/rolls-royce-dawn-rentnal-miami2.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/03/rolls-royce-dawn-rentnal-miami5.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/03/rolls-royce-dawn-rentnal-miami4.jpg',
      ],
      city: 'Los Angeles',
    },
    {
      id: 7,
      type: 'cabriolet',
      brand: 'LAMBORGHINI',
      model: 'HURACAN EVO',
      transmission: '7-speed, automatic',
      seats: 2,
      engine: '4,5 l., V8',
      to100km: '3,4 sec',
      horsePower: 570,
      year: 2021,
      color: 'black',
      priceForDay: 830,
      images: [
        'https://pugachev.miami/wp-content/uploads/2021/02/Lamborghini-luracan-evo-1.jpg',
        'https://pugachev.miami/wp-content/uploads/2021/02/Lamborghini-luracan-evo-2.jpg',
        'https://pugachev.miami/wp-content/uploads/2021/02/Lamborghini-luracan-evo-4.jpg',
        'https://pugachev.miami/wp-content/uploads/2021/02/Lamborghini-luracan-evo-5.jpg',
        'https://pugachev.miami/wp-content/uploads/2021/02/Lamborghini-luracan-evo-3.jpg',
      ],

      city: 'Los Angeles',
    },
    {
      id: 8,
      type: 'cabriolet',
      brand: 'MERCEDES-BENZ',
      model: 'SL BLACK',
      transmission: 'Automatic',
      seats: 5,
      engine: 'V8 Biturbo 5.5-liter',
      to100km: '5.2 sec',
      horsePower: 800,
      year: 2023,
      color: 'black',
      priceForDay: 980,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/03/IMG_9035.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/IMG_9034-1.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/IMG_9033-1.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/IMG_9037-1.jpg',
      ],

      city: 'Los Angeles',
    },
    {
      id: 9,
      type: 'cabriolet',
      brand: 'FERRARI',
      model: 'PORTOFINO',
      transmission: 'Automatic',
      seats: 4,
      engine: 'Twin-turbo 3.9L V8',
      to100km: '3.5 sec',
      horsePower: 800,
      year: 2021,
      color: 'red',
      priceForDay: 850,
      images: [
        'https://pugachev.miami/wp-content/uploads/2022/01/IMG_0583.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/01/Ferrari-Portofino_back2.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/01/Ferrari-Portofino_back.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/01/IMG_0579.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/01/IMG_0581.jpg',
      ],

      city: 'Dubai',
    },
    {
      id: 10,
      type: 'cabriolet',
      brand: 'BENTLEY',
      model: 'GTC MULLINER GOLD',
      transmission: 'Automatic, 8-speed',
      seats: 4,
      engine: '6,75L, V8',
      to100km: '3.9 sec',
      horsePower: 626,
      year: 2021,
      color: 'gold',
      priceForDay: 700,
      images: [
        'https://pugachev.miami/wp-content/uploads/2020/03/Bentley-Continental-GT-White-01.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/03/Bentley-Continental-GT-White-06.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/03/Bentley-Continental-GT-White-03.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/03/Bentley-Continental-GT-White-04.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/03/Bentley-Continental-GT-White-05.jpg',
      ],

      city: 'Los Angeles',
    },
    {
      id: 11,
      type: 'sedan',
      brand: 'MERCEDES',
      model: 'C63',
      transmission: '9-speed, automatic',
      seats: 4,
      engine: '4.0L AMG V8 Biturbo',
      to100km: '3.7 sec',
      horsePower: 503,
      year: 2019,
      color: 'grey',
      priceForDay: 399,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/03/eYVsFbOc.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/cU-DrvgO.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/AESg-Lgq.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/tDMZVTwq.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/dpVJuB_-.jpg',
      ],

      city: 'Dubai',
    },
    {
      id: 12,
      type: 'cabriolet',
      brand: 'ROLLS ROYCE',
      model: 'DAWN BLACK',
      transmission: 'Automatic 8-speed',
      seats: 4,
      engine: '6.6 L V12',
      to100km: '4,9 sec',
      horsePower: 563,
      year: 2020,
      color: 'black',
      priceForDay: 1000,
      images: [
        'https://pugachev.miami/wp-content/uploads/2021/02/rolls_b1.jpg',
        'https://pugachev.miami/wp-content/uploads/2021/02/rolls_b2.jpg',
        'https://pugachev.miami/wp-content/uploads/2021/02/rolls_b4.jpg',
        'https://pugachev.miami/wp-content/uploads/2021/02/rolls_b3.jpg',
        'https://pugachev.miami/wp-content/uploads/2021/02/rolls_b5.jpg',
      ],

      city: 'Dubai',
    },
    {
      id: 13,
      type: 'cabriolet',
      brand: 'MERCEDES',
      model: 'S CLASS 63',
      transmission: '	9-speed, automatic',
      seats: 5,
      engine: 'V8 biturbo, eight-cylinder',
      to100km: '3.5sec',
      horsePower: 585,
      year: 2020,
      color: 'black',
      priceForDay: 500,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/11/bmw_1.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/11/bmw_33.jpg',
        // 'https://pugachev.miami/wp-content/uploads/2019/11/Mercedes-s63-2020-3.jpeg',
        // 'https://pugachev.miami/wp-content/uploads/2019/11/Mercedes-s63-2020-4.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/bmw_2.jpg',
      ],

      city: 'Dubai',
    },
    {
      id: 14,
      type: 'super',
      brand: 'MCLAREN',
      model: '600LT',
      transmission: 'Automatic',
      seats: 2,
      engine: 'V8 biturbo, eight-cylinder',
      to100km: '3sec',
      horsePower: 641,
      year: 2022,
      color: 'blue',
      priceForDay: 950,
      images: [
        'https://pugachev.miami/wp-content/uploads/2023/09/mclaren-600lt-2022-1.jpg',
        'https://pugachev.miami/wp-content/uploads/2023/09/mclaren-600lt-2022-5.jpg',
        'https://pugachev.miami/wp-content/uploads/2023/09/mclaren-600lt-2022-3.jpg',
        'https://pugachev.miami/wp-content/uploads/2023/09/mclaren-600lt-2022-4.jpg',
        'https://pugachev.miami/wp-content/uploads/2023/09/mclaren-600lt-2022-6.jpg',
      ],

      city: 'Los Angeles',
    },
    {
      id: 15,
      type: 'super',
      brand: 'MCLAREN',
      model: '650S SPIDER',
      transmission: 'Automatic',
      seats: 2,
      engine: '3.8L V8',
      to100km: '3sec',
      horsePower: 641,
      year: 2022,
      color: 'blue',
      priceForDay: 800,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/03/D85_3002.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/m1.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/m2-e1566061386515.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/m3-e1566061459819.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/m4.jpg',
      ],

      city: 'Los Angeles',
    },
    {
      id: 16,
      type: 'super',
      brand: 'LAMBORGHINI',
      model: 'AVENTADOR',
      transmission: '6 Speed Automatic',
      seats: 2,
      engine: 'V12 6.5-liter',
      to100km: '2.5sec',
      horsePower: 544,
      year: 2022,
      color: 'orange',
      priceForDay: 1400,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/11/Rent-Lamborghini-Huracan-LP-610-in-Miami-1-obr.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Rent-Lamborghini-Huracan-LP-610-in-Miami-2-obr.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Rent-Lamborghini-Huracan-LP-610-in-Miami-3-obr.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Rent-Lamborghini-Huracan-LP-610-in-Miami-4-obr.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Rent-Lamborghini-Huracan-LP-610-in-Miami-5-obr.jpg',
      ],

      city: 'Los Angeles',
    },
    {
      id: 17,
      type: 'super',
      brand: 'LAMBORGHINI',
      model: 'HURACAN EVO',
      transmission: '	7-speed, automatic',
      seats: 2,
      engine: '4,5 l., V8',
      to100km: '3,4 sec',
      horsePower: 570,
      year: 2021,
      color: 'white',
      priceForDay: 875,
      images: [
        'https://pugachev.miami/wp-content/uploads/2022/12/lambo-huracan-evo-white-rental-miami-1.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/12/lambo-huracan-evo-white-rental-miami-2.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/12/lambo-huracan-evo-white-rental-miami-5.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/12/lambo-huracan-evo-white-rental-miami-6.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/12/lambo-huracan-evo-white-rental-miami-3.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/12/lambo-huracan-evo-white-rental-miami-4.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/12/lambo-huracan-evo-white-rental-miami-7.jpg',
      ],

      city: 'Dubai',
    },
    {
      id: 18,
      type: 'super',
      brand: 'FERRARI',
      model: 'GTB',
      transmission: '7-speed, automatic',
      seats: 2,
      engine: '4,5 l., V8',
      to100km: '3,4 sec',
      horsePower: 570,
      year: 2021,
      color: 'red',
      priceForDay: 1100,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/03/california_t_1.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/california_t_6_o.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/california_t_2.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/california_t_4.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/california_t_5.jpg',
      ],

      city: 'Dubai',
    },
    {
      id: 19,
      type: 'super',
      brand: 'FERRARI',
      model: 'F8',
      transmission: '7-speed dual-clutch automatic',
      seats: 2,
      engine: 'V8 Biturbo 3,9-liter',
      to100km: '2,8 sec',
      horsePower: 710,
      year: 2023,
      color: 'white',
      priceForDay: 2500,
      images: [
        'https://pugachev.miami/wp-content/uploads/2022/03/ferrari-f8-rentnal-miami-new1.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/03/ferrari-f8-rentnal-miami-new4.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/03/ferrari-f8-rentnal-miami-new2.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/03/ferrari-f8-rentnal-miami-new3.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/03/ferrari-f8-rentnal-miami-new5.jpg',
      ],

      city: 'Dubai',
    },
    {
      id: 20,
      type: 'super',
      brand: 'AUDI',
      model: 'R8 V10 COUPE',
      transmission: '7-speed automatic',
      seats: 2,
      engine: 'V10',
      to100km: '3,8 sec',
      horsePower: 540,
      year: 2018,
      color: 'white',
      priceForDay: 1800,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/11/Audi-R8-V10-2018-coupe6.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Audi-R8-V10-2018-coupe5.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Audi-R8-V10-2018-coupe4.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Audi-R8-V10-2018-coupe.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Audi-R8-V10-2018-coupe2.jpeg',
      ],

      city: 'Los Angeles',
    },
    {
      id: 21,
      type: 'super',
      brand: 'TESLA ',
      model: 'MODEL X',
      transmission: '	Robot, 7',
      seats: 2,
      engine: '3.8L V8',
      to100km: '3.2 sec',
      horsePower: 540,
      year: 2018,
      color: 'white',
      priceForDay: 250,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/03/02-X4-e1564013166679.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/DDS_7717-X4-e1564013329729.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/04-X4-e1564013288904.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/DSC00070-X4-e1564013242726.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/DDS_7747-X4-e1564013256823.jpg',
      ],

      city: 'Dubai',
    },
    {
      id: 22,
      type: 'super',
      brand: 'FORD',
      model: 'MUSTANG GT',
      transmission: '	Robot, 7',
      seats: 2,
      engine: '3.8L V8',
      to100km: '3.2 sec',
      horsePower: 570,
      year: 2018,
      color: 'black',
      priceForDay: 850,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/09/Mustang-rent-Miami-2.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/09/Mustang-rent-Miami-3.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/09/Mustang-rent-Miami-4.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/09/Mustang-rent-Miami-5.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/09/Mustang-rent-Miami-6-1.jpg',
      ],

      city: 'Los Angeles',
    },
    {
      id: 23,
      type: 'super',
      brand: 'FERRARI',
      model: 'F12 BERLINETTA',
      transmission: '7-speed robotic',
      seats: 2,
      engine: '6.3L V12',
      to100km: '3.1 sec',
      horsePower: 740,
      year: 2018,
      color: 'black',
      priceForDay: 800,
      images: [
        'https://pugachev.miami/wp-content/uploads/2020/02/Ferrari-Berlinetta-6.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/02/Ferrari-Berlinetta-2.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/02/Ferrari-Berlinetta-3.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/02/Ferrari-Berlinetta-4.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/02/Ferrari-Berlinetta-5.jpg',
      ],

      city: 'Dubai',
    },
    {
      id: 24,
      type: 'super',
      brand: 'LAMBORGHINI',
      model: 'HURACAN SPYDER',
      transmission: 'Automatic',
      seats: 2,
      engine: '5.2L V10',
      to100km: '2.9 sec',
      horsePower: 610,
      year: 2018,
      color: 'black',
      priceForDay: 1200,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/03/9-e1554575023962.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/6-e1554575003239.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/4-e1554575034756.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/03/2-e1554575042544.jpg',
      ],

      city: 'Los Angeles',
    },
    {
      id: 25,
      type: 'super',
      brand: 'BMW',
      model: 'I8 ROADSTER',
      transmission: 'Automatic',
      seats: 2,
      engine: 'turbocharged 1.5-liter',
      to100km: '4.0 sec',
      horsePower: 374,
      year: 2019,
      color: 'white',
      priceForDay: 400,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/11/i8-white-miami-1.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/i8-white-miami-2.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/i8-white-miami-3.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/i8-white-miami-4.jpeg',
        'https://pugachev.miami/wp-content/uploads/2019/11/i8-white-miami-5.jpeg',
      ],

      city: 'Dubai',
    },
    {
      id: 26,
      type: 'super',
      brand: 'LAMBORGHINI',
      model: 'AVENTADOR MATTE',
      transmission: '6 Speed Automatic',
      seats: 2,
      engine: '	V12 6.5-liter',
      to100km: '2.5 sec',
      horsePower: 544,
      year: 2019,
      color: 'red',
      priceForDay: 780,
      images: [
        'https://pugachev.miami/wp-content/uploads/2020/01/Lamborghini-huracan-performance-5.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/01/Lamborghini-huracan-performance-1.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/01/Lamborghini-huracan-performance-3.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/01/Lamborghini-huracan-performance-2.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/01/Lamborghini-huracan-performance-4.jpg',
      ],

      city: 'Los Angeles',
    },
    {
      id: 27,
      type: 'sedan',
      brand: 'ROLLS-ROYCE',
      model: 'CULLINAN BLACK BADGE',
      transmission: 'Automatic 8-speed',
      seats: 4,
      engine: '6.6 L V12',
      to100km: '4,9 sec',
      horsePower: 563,
      year: 2022,
      color: 'white',
      priceForDay: 1300,
      images: [
        'https://pugachev.miami/wp-content/uploads/2023/09/rolls-royce-cullinan-2022-black-badge-1.jpg',
        'https://pugachev.miami/wp-content/uploads/2023/09/rolls-royce-cullinan-2022-black-badge-4.jpg',
        'https://pugachev.miami/wp-content/uploads/2023/09/rolls-royce-cullinan-2022-black-badge-2.jpg',
        'https://pugachev.miami/wp-content/uploads/2023/09/rolls-royce-cullinan-2022-black-badge-3.jpg',
        'https://pugachev.miami/wp-content/uploads/2023/09/rolls-royce-cullinan-2022-black-badge-6.jpg',
        'https://pugachev.miami/wp-content/uploads/2023/09/rolls-royce-cullinan-2022-black-badge-7.jpg',
        'https://pugachev.miami/wp-content/uploads/2023/09/rolls-royce-cullinan-2022-black-badge-7.jpg',
      ],

      city: 'Dubai',
    },
    {
      id: 28,
      type: 'sedan',
      brand: 'ROLLS-ROYCE',
      model: 'CULLINAN BLACK BADGE',
      transmission: 'Automatic',
      seats: 5,
      engine: '4.4-liter Turbo V8',
      to100km: '4,9 sec',
      horsePower: 617,
      year: 2022,
      color: 'black',
      priceForDay: 450,
      images: [
        'https://pugachev.miami/wp-content/uploads/2020/03/Rolls-Royce-Dawn-Blue_1.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/03/Rolls-Royce-Dawn-Blue_3.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/03/Rolls-Royce-Dawn-Blue_2.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/03/Rolls-Royce-Dawn-Blue_4.jpg',
        'https://pugachev.miami/wp-content/uploads/2020/03/Rolls-Royce-Dawn-Blue_5.jpg',
      ],

      city: 'Los Angeles',
    },
    {
      id: 29,
      type: 'sedan',
      brand: 'MERCEDES-BENZ',
      model: 'G63',
      transmission: 'Automatic',
      seats: 5,
      engine: 'V8 Biturbo 5.5-liter',
      to100km: '5,2 sec',
      horsePower: 800,
      year: 2022,
      color: 'black',
      priceForDay: 699,
      images: [
        'https://pugachev.miami/wp-content/uploads/2022/12/mercedes-benz-g63-2022-black-1.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/12/mercedes-benz-g63-2022-black4.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/12/mercedes-benz-g63-2022-black3.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/12/mercedes-benz-g63-2022-black5.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/12/mercedes-benz-g63-2022-black2.jpg',
      ],

      city: 'Dubai',
    },
    {
      id: 30,
      type: 'sedan',
      brand: 'MERCEDES-BENZ',
      model: 'AMG G63 – NEON EDITION',
      transmission: 'Automatic',
      seats: 5,
      engine: 'V8 Biturbo 5.5-liter',
      to100km: '5,2 sec',
      horsePower: 800,
      year: 2021,
      color: 'neon',
      priceForDay: 790,
      images: [
        'https://pugachev.miami/wp-content/uploads/2022/01/mercedes-benz-amg-g63-2021-1-o.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/01/mercedes-benz-amg-g63-2021-2-o.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/01/mercedes-benz-amg-g63-2021-5-o.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/01/mercedes-benz-amg-g63-2021-4-o.jpg',
        'https://pugachev.miami/wp-content/uploads/2022/01/mercedes-benz-amg-g63-2021-3-o.jpg',
      ],

      city: 'Los Angeles',
    },
    {
      id: 31,
      type: 'sedan',
      brand: 'LAMBORGHINI',
      model: 'URUS',
      transmission: 'Automatic',
      seats: 5,
      engine: '	4.0L Biturbo V8',
      to100km: '3,4 sec',
      horsePower: 800,
      year: 2019,
      color: 'black',
      priceForDay: 1000,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/11/Rent-Lamborghini-Urus-Black-in-Miami-2_obr.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Rent-Lamborghini-Urus-Black-in-Miami-1_obr.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Rent-Lamborghini-Urus-Black-in-Miami-3_obr.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Rent-Lamborghini-Urus-Black-in-Miami-5_obr.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/11/Rent-Lamborghini-Urus-Black-in-Miami-4_obr.jpg',
      ],

      city: 'Dubai',
    },
    {
      id: 32,
      type: 'sedan',
      brand: 'RANGE ROVER',
      model: 'HSE',
      transmission: '	Automatic 7G-TRONIC 7-speed',
      seats: 5,
      engine: '	4.0L Biturbo V8',
      to100km: '6,5 sec',
      horsePower: 416,
      year: 2018,
      color: 'black',
      priceForDay: 800,
      images: [
        'https://pugachev.miami/wp-content/uploads/2019/09/range-rover-rent-miami-6.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/09/range-rover-rent-miami.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/09/range-rover-rent-miami-4.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/09/range-rover-rent-miami-3.jpg',
        'https://pugachev.miami/wp-content/uploads/2019/09/range-rover-rent-miami-5.jpg',
      ],

      city: 'Dubai',
    },
  ];

  getMyDataArray(): any[] {
    return this.myDataArray;
  }

  addData(data: any): void {
    this.myDataArray.push(data);
  }
}
